# Generated by Django 4.2.13 on 2026-10-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('issue_created', 'Issue Created'), ('status_update', 'Status Update'), ('upvote', 'Upvote'), ('duplicate', 'Duplicate Issue'), ('registration_approved', 'Registration Approved'), ('registration_rejected', 'Registration Rejected')], max_length=30),
        ),
    ]
