# Generated by Django 4.2.13 on 2026-10-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='authority_decision',
            field=models.CharField(blank=True, choices=[('invalid', 'Invalid'), ('fake', 'Fake')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='authority_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
