# Generated by Django 4.2.13 on 2026-10-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_authority_decision_issue_authority_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ai_duplicate_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
