# Generated by Django 4.2.13 on 2026-10-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_add_ai_duplicate_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ai_image_match_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='issue',
            name='ai_is_image_match',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='ai_severity_basis',
            field=models.CharField(blank=True, default='text_only', max_length=30),
        ),
        migrations.AddField(
            model_name='issue',
            name='ai_severity_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='issue',
            name='ai_validation_status',
            field=models.CharField(blank=True, default='valid', max_length=20),
        ),
    ]
