# Generated by Django 4.2.13 on 2026-10-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issue_ai_image_match_reason_issue_ai_is_image_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
